apisix:
  enabled: true
  global:
    imageRegistry: 192.168.44.140:35000
  image:
    registry: 192.168.44.140:35000
    repository: bitnami/apisix
    tag: 3.9.1-debian-12-r8

  dashboard:
    enabled: true
    username: admin
    password: admin_password

  ingressController:
    enabled: true
    

# Add MySQL dependency
mysql:
  enabled: true
  image:
    registry: 192.168.44.140:35000
    repository: bitnami/mysql
    tag: 8.0.39
  auth:
    rootPassword: mysql-root_password
    database: keycloak
    username: keycloak
    password: keycloak_password




# Keycloak configuration to use MySQL
keycloak:
  enabled: true

  global:
    imageRegistry: 192.168.44.140:35000
 
  image:
    repository: bitnami/keycloak
    tag: 25.0.2-debian-12-r2
  auth:
    adminUser: admin
    adminPassword: admin_password
  
  postgresql:
    enabled: false

  externalDatabase:
    host: reg-apisix-mysql.default.svc.cluster.local
    port: 3306
    user: keycloak
    database: keycloak
    password: keycloak_password

  
  extraEnvVars:
    - name: KC_DB # override values from the conf file
      value: 'mysql'
    - name: KC_DB_URL
      value: 'jdbc:mysql://reg-apisix-mysql.default.svc.cluster.local:3306/keycloak'
    - name: KC_HOSTNAME_DEBUG
      value: 'true'
    

  containerSecurityContext:
    enabled: false

 
