apisix:
  enabled: false

# Disable PostgreSQL
postgresql:
  enabled: false

# Add MySQL dependency
  mysql:
    enabled: true
  auth:
    rootPassword: mysql-root_password
    database: keycloak
    username: keycloak
    password: keycloak_password



# Keycloak configuration to use MySQL
keycloak:
  enabled: false
  # Disable PostgreSQL
  externalDatabase:
    host: "10.152.183.32"
    port: 3306
    user: keycloak
    database: keycloak
    existingSecret: reg-apisix-mysql
  extraEnvVars:
    - name: KC_DB # override values from the conf file
      value: 'mysql'
    - name: KC_DB_URL
      value: 'jdbc:mysql://10.152.183.32:3306/keycloak;'
  postgresql:
    enabled: false
  mysql:
    enabled: true

